function generateLegalNoticeHTML() {
    return /*html*/ `
      <div class="close-icon-cont">
          <div onclick="closePopUp()" class="close-icon">X</div>
      </div>
  
      <div class="legal-notice-content">
      <h2>Legal Notice</h2>
      <div class='legal-notice-text'>
          <p>Information in accordance with Section 5 DDG</p>
          <p>Anna Fritz <br> 
              Plantagenweg 13<br> 
              31303 Burgdorf <br></p>
          <p><strong>Represented by:</strong><br>
              Anna Fritz<br></p>
          <p><strong>Contact:</strong><br>
              Phone: +49 15785094457<br>
              E-mail: <a class="email" href='mailto:anna_eida@gmx.de'>anna_eida@gmx.de</a></br></p>
          <p><strong>Disclaimer:</strong><br><br>
              <strong>Liability for content</strong><br><br>
              The content of our pages has been created with the utmost care. However, we cannot guarantee the accuracy, completeness, or timeliness of the content. As a service provider, we are responsible for our own content on these pages in accordance with Section 7(1) DDG under general law. According to Sections 8 to 10 DDG, we are not obligated as a service provider to monitor transmitted or stored third-party information or to investigate circumstances that indicate illegal activity. Obligations to remove or block the use of information under general laws remain unaffected. However, liability in this regard is only possible from the moment of knowledge of a specific infringement. Upon becoming aware of such violations, we will remove this content immediately.<br><br>
              <strong>Liability for links</strong><br><br>
              Our offer contains links to external third-party websites, over whose content we have no control. Therefore, we cannot assume any liability for these external contents. The respective provider or operator of the linked pages is always responsible for the content. The linked pages were checked for possible legal violations at the time of linking. Illegal content was not recognizable at the time of linking. Permanent content control of the linked pages is not reasonable without concrete indications of a legal violation. If we become aware of any legal infringements, we will remove such links immediately.<br><br>
              <strong>Copyright</strong><br><br>
              The content and works created by the site operators on these pages are subject to German copyright law. Duplication, processing, distribution, and any kind of exploitation outside the limits of copyright law require the written consent of the respective author or creator. Downloads and copies of this site are permitted for private, non-commercial use only. Insofar as the content on this site was not created by the operator, third-party copyrights are respected. In particular, third-party content is marked as such. Should you nevertheless become aware of a copyright infringement, we ask for an appropriate notice. Upon becoming aware of legal violations, we will remove such content immediately.<br><br>
              <strong>Data protection</strong><br><br>
              The use of our website is generally possible without providing personal data. Insofar as personal data (such as name, address, or e-mail address) is collected on our pages, this is always done, as far as possible, on a voluntary basis. This data will not be passed on to third parties without your express consent.<br>
              We point out that data transmission over the Internet (e.g., communication by e-mail) can have security vulnerabilities. Complete protection of data from access by third parties is not possible.<br>
              The use of contact data published in the context of the legal notice obligation by third parties for sending unsolicited advertisements and information materials is hereby expressly prohibited. The site operators expressly reserve the right to take legal action in the event of unsolicited advertising, such as spam e-mails.<br><br>
              <strong>Google Analytics</strong><br><br>
              This website uses Google Analytics, a web analytics service provided by Google Inc. ("Google"). Google Analytics uses so-called "cookies," which are text files placed on your computer to help analyze how you use the website. The information generated by the cookie about your use of this website (including your IP address) is transmitted to a Google server in the USA and stored there. Google will use this information to evaluate your use of the website, to compile reports on website activity for website operators, and to provide other services related to website activity and internet usage. Google may also transfer this information to third parties if required by law or if third parties process this data on behalf of Google. Google will not associate your IP address with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser; however, please note that if you do this, you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.<br><br>
              <strong>Google AdSense</strong><br><br>
              This website uses Google AdSense, a web advertising service of Google Inc., USA ("Google"). Google AdSense uses so-called "cookies" (text files) that are stored on your computer to analyze your use of the website. Google AdSense also uses so-called "web beacons" (small invisible graphics) to collect information. Through the use of the web beacon, simple actions such as visitor traffic on the website can be recorded and collected. The information generated by the cookie and/or web beacon about your use of this website (including your IP address) is transmitted to a Google server in the USA and stored there. Google will use this information to evaluate your use of the website regarding advertisements, to compile reports on website activities and ads for website operators, and to provide other services related to website and internet usage. Google may also transfer this information to third parties if required by law or if third parties process this data on behalf of Google. Google will not associate your IP address with any other data held by Google. You can prevent the storage of cookies on your hard drive and the display of web beacons by selecting "do not accept cookies" in your browser settings (in Internet Explorer under "Tools > Internet Options > Privacy > Settings"; in Firefox under "Tools > Settings > Privacy > Cookies"); however, please note that if you do this, you may not be able to use the full functionality of this website. By using this website, you consent to the processing of data about you by Google in the manner and for the purposes set out above.</p><br>
      </div>
  </div>
  
     `;
}

function generateControlLayoutHTML() {
    return /*html*/ `
      <div class="close-icon-cont">
          <div onclick="closePopUp()" class="close-icon">X</div>
      </div>
      <div class="control-layout-cont">
          <div class="control-layout-keyboard">
          <h2>Control Layout</h2>
          <div class="layout-btns">
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-left.svg" alt="arrow left">
                  </div>
                  <h4>walk left</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-right.svg" alt="arrow left">
                  </div>
                  <h4>walk right</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/space-key.svg" alt="arrow left">
                  </div>
                  <h4>jump</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <div class="key-d white">D</div>
                  </div>
                  <h4>throw bottle</h4>
              </div>
          </div>
          </div>
          <div>
          <h2>Mobile</h2>
          <div class="layout-btns">
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-left.svg" alt="arrow left">
                  </div>
                  <h4>walk left</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-right.svg" alt="arrow left">
                  </div>
                  <h4>walk right</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-up.svg" alt="arrow left">
                  </div>
                  <h4>jump</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/bottle.svg" alt="arrow left">
                  </div>
                  <h4>throw bottle</h4>
              </div>
          </div>
          </div>
      </div> 
      <!-- <div class="control-layout-cont">
          <h2>Mobile</h2>
          <div class="layout-btns">
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-left.svg" alt="arrow left">
                  </div>
                  <h4>walk left</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-right.svg" alt="arrow left">
                  </div>
                  <h4>walk right</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/arrow-up.svg" alt="arrow left">
                  </div>
                  <h4>jump</h4>
              </div>
              <div class="btn-cont">
                  <div class="panel-icon-cont">
                      <img class="panel-icon" src="../img/icons/bottle.svg" alt="arrow left">
                  </div>
                  <h4>throw bottle</h4>
              </div>
          </div>
      </div>  
    -->
      `;
}
  
function generatePepeStoryHTML() {
    return /*html*/ `
        <div class="close-icon-cont">
            <div onclick="closePopUp()" class="close-icon">X</div>
        </div>

          <div class="pepe-story">
              <h2>Pepe Peligroso</h2>
              <span>&</span>
              <h3>the Invasion of <br>El pollo loco</h3>
              <div class=''>
              <p>High up in the sun-scorched heights of the Sierra Madre lies a small, almost forgotten village called Real de Catorce. Once a magnificent silver mining town, its people toiled deep beneath the earth in search of fortune. But as silver prices plummeted and the mines dried up, the town’s glory faded away. Today, it’s a ghost town, surrounded by the unforgiving desert of San Luis Potosí, with only a handful of inhabitants left, living in quiet harmony with the past – until that fateful day when everything changed.<br><br>
                One morning, an ominous clucking echoed through the dusty streets. The villagers awoke in fear as hundreds of chickens descended upon the town. But these were no ordinary chickens. They were faster, more aggressive, and deadlier than anything anyone had ever seen. Leading them was the legendary <strong>El Pollo Loco</strong> – a colossal, monstrous creature that seemed to spawn an endless wave of new chickens, as if sent by the depths of hell itself.<br><br>
                No one dared to face the crazed chicken army. The villagers fled, barricading themselves in their homes or hiding in the abandoned mines. But one man stayed behind – the brave Pepe Peligroso, an unassuming yet fiery-hearted soul with the courage of a hero. Pepe was the owner of the town’s last remaining factory, where he had once produced spicy salsa bottles to sell to the few tourists who wandered into the ghost town.<br><br>
                Pepe knew he had no choice. These chickens weren’t just a nuisance – they were a threat to the entire village. While the others cowered in fear, Pepe resolved to take matters into his own hands. Luckily, he had an unusual weapon: his salsa factory. He realized that the fiery salsa he produced in vast quantities could be the perfect ammunition against the chicken invasion. With the power of chili heat, he could drive the crazed chickens away – or at least slow them down long enough to save the village.<br><br>
                The chickens, however, underestimated Pepe Peligroso. Armed with salsa sauce-bottles and secret fiery recipes known only to him, Pepe took on the rampaging chicken army. Every salsa shot he fired sizzled through the air, and the chickens recoiled as though whipped by flames. But Pepe knew that stopping the smaller chickens wasn’t enough – he had to defeat <strong>El Pollo Loco</strong>, the source of this strange invasion.<br><br>
                Join Pepe Peligroso on his wild mission to save the village and defeat <strong>El Pollo Loco</strong>. Use spicy salsa weapons, build new gadgets, and discover the chicken army’s weaknesses. It’s a race against time – and against a clucking horde. But with courage, humor, and plenty of salsa, Pepe will triumph.<br><br>
                Because one thing is certain: in Real de Catorce, things are about to get very, very hot.</p>
          </div>
     `;
}
